const mongoose = require("mongoose");

/**
 * @property id: item random generated id
 * @property by: item author
 * @property title
 * @property type: item type (news, show, or ask)
 * @property url: item url if it is news or show
 * @property domain: domain of the url (useful for getting item by domain name)
 * @property text: item content if type is ask
 * @property point: karma for item. gotten by num of vote
 * @property score: algoritmitically generated by formula in order to sort item on the home page by popular
 * @property commentCount
 * @property created: UNIX timestamp on when is the item created
 * @property dead: item has been killed by moderator
 */
const ItemSchema = new mongoose.Schema({
    id: {
        type: String,
        unique: true,
        required: true,
    },

    by: {
        type: String,
        required: true,
    },
    title: {
        type: String,
        required: true,
    },
    type: {
        type: String,
        required: true,
    },

    url: String,
    domain: String,
    text: String,

    points: {
        type: Number,
        default: 1,
        min: 1,
    },
    score: {
        type: Number,
        default: 0,
    },
    commentCount: {
        type: Number,
        default: 0,
    },

    created: Number,
    dead: {
        type: Boolean,
        default: false,
    },
});

ItemSchema.index({ id: 1, by: 1, type: 1, domain: 1, points: 1 });

module.exports = mongoose.model("Item", ItemSchema);
